## This template is used by the following repos:
## 
## 3722-nautilus-commerce-angular-js

parameters:
  - name: workingDirectory
    type: string
  - name: commandPublish
    type: string
    default: ''

steps:
  - ${{if not(parameters.commandPublish)}}: #Ejecuta el task cuando el parametro esté vacio
    - task: Npm@1
      displayName: Publish
      inputs:
        command: 'publish'
        workingDir: '${{parameters.workingDirectory}}'
        customRegistry: 'useFeed'
        customFeed: $(feed_id)
  
  - ${{if parameters.commandPublish}}: #Ejecuta el task cuando el parametro no esté vacio
    - task: Npm@1
      displayName: Publish
      inputs:
        command: 'custom'
        verbose: true
        workingDir: '${{parameters.workingDirectory}}'
        customCommand: '${{parameters.commandPublish}}'
        customRegistry: 'useFeed'
        customFeed: $(feed_id)

  - task: DeleteFiles@1
    condition: succeeded()
    displayName: Clean workspace
    inputs:
      Contents: '**/*'