#Used on 4002-gestion-ingreso-vp-lambdas pipeline

parameters:
  - name: workingDirectory
    type: string
    default: '.'
  - name: commandBuild
    type: string
  - name: containerImage
    type: string
    default: 'maven:3.6.3-jdk-11-openj9'
  - name: buildPath
    type: string

jobs:
  - job: Build
    container: 
      image: ${{parameters.containerImage}}
    workspace:
      clean: all
    steps:
    - checkout: self
      displayName: 'Clone repository'
      fetchDepth: 1

    - task: Maven@3
      displayName: 'Build'
      inputs:
        mavenPomFile: '${{parameters.workingDirectory}}/pom.xml'
        goals: '${{parameters.commandBuild}}'
        publishJUnitResults: false
    
    - publish: '${{ parameters.buildPath }}'
      artifact: Build